EWallet/Controllers/PiggyBankController.cs

using EWallet.BusinessLogic.Implementation.Incomes;
using EWallet.BusinessLogic.Implementation.Incomes.Validations;
using EWallet.BusinessLogic.Implementation.PiggyBanks;
using EWallet.BusinessLogic.Implementation.PiggyBanks.Validations;
using EWallet.BusinessLogic.Implementation.PiggyBanks.ViewModel;
using EWallet.BusinessLogic.Implementation.Users;
using EWallet.Code;
using EWallet.Code.ExtensionMethods;
using EWallet.Common.Exceptions;
using EWallet.DataAccess.Enums;
using EWallet.WebApp.Code.Base;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EWallet.Controllers
{
    [Authorize(Roles = "User")]
    public class PiggyBankController : BaseController
    {

        private readonly PiggyBankService _piggyBankService;
        private readonly CreatePiggyBankValidator _createPiggyBankValidator;
        private readonly EditPiggyBankValidator _editPiggyBankValidator;
        private readonly CreatePiggyBanksIncomeValidator _createPiggyBanksIncomeValidator;
        private readonly IncomeService _incomesService;
        private readonly UserService _userService;

        public PiggyBankController(ControllerDependencies dependencies
            , PiggyBankService piggyBankService
            , CreatePiggyBankValidator createPiggyBankValidator
            , EditPiggyBankValidator editPiggyBankValidator
            , IncomeService incomesService
            , CreatePiggyBanksIncomeValidator createPiggyBanksIncomeValidator,
            UserService userService) :
            base(dependencies)
        {
            _piggyBankService = piggyBankService;
            _createPiggyBankValidator = createPiggyBankValidator;
            _editPiggyBankValidator = editPiggyBankValidator;
            _incomesService = incomesService;
            _createPiggyBanksIncomeValidator = createPiggyBanksIncomeValidator;
            _userService = userService;
        }



        public async Task<IActionResult> Index()
        {
            var personalPiggyBanks = await _piggyBankService.GetPersonalPiggyBanks();
            var collaborativePiggyBanks = await _piggyBankService.GetCollaborativePiggyBanks();
            var allIncomes = await _incomesService.GetIncomesAsSelectListItems();

            foreach (var piggyBank in personalPiggyBanks)
            {
                var collaborators = await _piggyBankService.GetCollaborators(piggyBank.Id);             
                piggyBank.Collaborators = collaborators;
            }

            return View(new DisplayPiggyBanksViewModel
            {
                CurrentUserId = CurrentUserViewModel.Id,
                PersonalPiggyBanks = personalPiggyBanks,
                CollaborativePiggyBanks = collaborativePiggyBanks,
                Incomes = allIncomes,
            }); 
        }




        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CreatePiggyBankViewModel model)
        {
            if (model == null)
            {
                return View("Error_NotFound");                                                                                                                                                                                          
            }

            ValidationResult validateResultPiggyBanksIncome = new ValidationResult();
            for (int index = 0; index < model.PiggyBanksIncomes.Count; index++)
            {
                var incomeValidationResult = _createPiggyBanksIncomeValidator.Validate(model.PiggyBanksIncomes[index]);
                if (!incomeValidationResult.IsValid)
                {
                    validateResultPiggyBanksIncome.Errors.AddRange(incomeValidationResult.Errors);
                }
            }


            var validateResult = _createPiggyBankValidator.Validate(model);
            if (!validateResult.IsValid || !validateResultPiggyBanksIncome.IsValid)
            {
                validateResult.Errors.AddRange(validateResultPiggyBanksIncome.Errors);
                return Ok(validateResult.GetErrorsResult());
            }
            else
            {
                await _piggyBankService.CreatePiggyBank(model);
                return Ok(new { });
            }
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var piggyBank = await _piggyBankService.GetPiggyBankToEdit(id);
            return Ok(piggyBank);
        }

      

        [HttpPost("PiggyBank/Delete")]
        public async Task<IActionResult> DeletePost( int id)
        {
            await _piggyBankService.DeletePiggyBank(id);
            return Ok(new { });
        }


        [HttpPost("PiggyBank/DeleteCollaborationById")]
        public async Task<IActionResult> DeleteCollaboration(int piggyBankId)
        {
            await _piggyBankService.DeleteCollaboration(piggyBankId);
            return Ok(new {});
        }

        [HttpPost("PiggyBank/DeleteCollaboration")]
        public async Task<IActionResult> DeleteCollaborationPost([FromBody] PiggyBankCollaborationViewModel model)
        {
            await _piggyBankService.DeleteCollaborationPost(model);
            return Ok(new { });
        }


        [HttpGet]
        public async Task<IActionResult> Break(int id)
        {
            var piggyBank = await _piggyBankService.GetPiggyBankToEdit(id);
            return Ok(piggyBank);
        }



        [HttpPost("PiggyBank/Break")]
        public async Task<IActionResult> BreakPost(int id)
        {
            await _piggyBankService.BreakPiggyBank(id);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var piggyBank = await _piggyBankService.GetPiggyBankToEdit(id);
            return Ok(piggyBank);
        }



        [HttpPost]
        public async Task<IActionResult> Edit([FromBody] EditPiggyBankViewModel model)
        {
           
            ValidationResult validateResultPiggyBanksIncome = new ValidationResult(); ;
            for (int index = 0; index < model.PiggyBanksIncomes.Count; index++)
            {
                var incomeValidationResult = _createPiggyBanksIncomeValidator.Validate(model.PiggyBanksIncomes[index]);
                if (!incomeValidationResult.IsValid)
                {
                    validateResultPiggyBanksIncome.Errors.AddRange(incomeValidationResult.Errors);
                }
            }

            var validateResult = _editPiggyBankValidator.Validate(model);
            if (!validateResult.IsValid || !validateResultPiggyBanksIncome.IsValid)
            {
                validateResult.Errors.AddRange(validateResultPiggyBanksIncome.Errors);
                return Ok(validateResult.GetErrorsResult());
            }
            else
            {
                await _piggyBankService.EditPiggyBank(model);
                return Ok(new { });
            }

        }




        [HttpGet]
        public async Task<IActionResult> EditCollaborativePiggyBank(int id)
        {
            var piggyBank = await _piggyBankService.GetCollaborativePiggyBankToEdit(id);
            return Ok(piggyBank);
        }





        [HttpPost]
        public async Task<IActionResult> EditCollaborativePiggyBank([FromBody] EditCollaborativePiggyBankViewModel model)
        {
            foreach (var cpb in model.CollaborativePiggyBankIncomes)
            {
                var validateResult = _createPiggyBanksIncomeValidator.Validate(cpb);
                if (!validateResult.IsValid)
                {
                    return Ok(validateResult.GetErrorsResult());
                }
            }

            await _piggyBankService.EditCollaborativePiggyBank(model);
            return Ok(new { });

        }



        [HttpGet]
        public async Task<IActionResult> GetAlmostCompletedPiggyBanks()
        {
            var incomes = await _piggyBankService.GetAlmostCompletedPiggyBanks();
            return Ok(incomes);
        }


        [HttpGet]
        public async Task<IActionResult> GetNearDueDatePiggyBanks()
        {
            var incomes = await _piggyBankService.GetNearDueDatePiggyBanks();
            return Ok(incomes);
        }


        [HttpGet]
        public async Task<IActionResult> GetCollaborators(int piggyBankId)
        {
            var collabs = await _piggyBankService.GetCollaborators(piggyBankId);
            return Ok(collabs);
        }


        [HttpGet]
        public async Task<IActionResult> GetNonCollaborators(int piggyBankId,string name)
        {
            var nonCollabs = await _piggyBankService.GetNonCollaborators(piggyBankId,name ?? "");
            return Ok(nonCollabs);
        }


        [HttpPost]
        public async Task<IActionResult> AddCollaborator([FromBody] PiggyBankCollaborationViewModel model)
        {
            try
            {
                await _piggyBankService.AddCollaborator(model);
            }
            catch (Exception ex)
            {
                var error = new ErrorResultItem()
                {
                    ErrorMessage = "The new collaboration couldn't be introduced"
                };

                return Ok(new ErrorsResult { Errors = new List<ErrorResultItem> { error } });
            }
            
            return Ok(new { });
            
        }


    }
}

EWallet/Views/PiggyBank/Index.cshtml
@using Newtonsoft.Json;
@using EWallet.Common.Enums;
@model EWallet.BusinessLogic.Implementation.PiggyBanks.ViewModel.DisplayPiggyBanksViewModel


@{
    ViewData["Title"] = "PiggyBanks";
    ViewData["Class"] = "PiggyBank-Page";

}
<head>
    

</head>

<div class="text-center">
    <div class="pagesHeaderPB">
    <h1 class="display-4">Piggy Banks</h1>

    <!--Create PiggyBank button-->
    <div class="form-group">
        <button type="button" id="addPiggyBankButton" class="btn btn-primary btn-lg" data-toggle="modal" data-target=".createOrEditPiggyBank"
                onclick="createOrEditPiggyBank('', getIncomes())">
            Add new PiggyBank
        </button>
    </div>

    </div>

    <div class="modal fade createOrEditPiggyBank" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered" style="min-width: 70%">
            <div class="modal-content">
                <div class="row">
                    <div class="col-md-6" id="createOrEditPiggyBankDiv">
                        <div id="pbTitleDiv">
                        <span id="pbTitle">Piggy bank details </span>
                        </div>
                    </div>
                    <div class="col-md-6" id="incomeDetails">
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!--Edit Collaborative PiggyBank-->


    <div class="modal fade editCollaborativePiggyBank" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content col-md-10 ">
                <div class="row">
                    <div id="editCollaborativePiggyBankDiv">
                        <span id="incomesTitle">ASSOCIATED INCOMES</span>
                        
                    </div>
                    
                </div>
            </div>
        </div>
    </div>




    <!--Add friend -->
    <div class="modal fade addFriendModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" style="min-width:30%;">
            <div class="modal-content">
                <div class="row">
                    <div class="col-md-12" id="addFriendModalDiv">

                    </div>
                </div>
            </div>
        </div>
    </div>





    <div id="PiggyBanksContainer">
        <div id="personalPB">Personal Piggy Banks</div>
        <div class="row">
            <div id="personalPiggyBanks">
            @foreach (var item in Model.PersonalPiggyBanks)
            {
                <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                            <h4 class="card-title card-header headerPB">@item.PiggyBankDescription</h4>
                            <h6  class="card-subtitle mb-2 text-muted piggyBankStatus">Status : @item.PiggyBankStatusName</h6>
                            <p class="card-text"><span style="font-size: 1.4em;">@item.CurrentBalance $ </span>
                                /@item.TargetSum $</p>



                        <div class="deleteButtonDiv">
                            <button type="button" data-toggle="modal" data-target=".deletePiggyBank"
                                    class="btn btn-primary deleteButton" onclick="getPiggyBankDataToDelete(@item.Id)">
                                    <i class="bi bi-trash"></i>

                             
                            </button>

                        </div>


                        <div class="editButtonDiv">


                            <button type="button" data-toggle="modal" data-target=".createOrEditPiggyBank"
                                    class="btn btn-primary editButton"
                                    onclick="createOrEditPiggyBank(@item.Id, getIncomes())">
                                    <i class="bi bi-pencil-fill"></i>
                            </button>

                        </div>



                            <div class="editButtonDiv">


                                <button type="button" data-toggle="modal" data-target=".addFriendModal"
                                        class="btn btn-primary editButton"
                                        onclick="editCollaborators(@item.Id)">
                                    <i class="bi bi-person-plus-fill"></i>
                                </button>

                            </div>



                            @if (item.PiggyBankStatus == (int)PiggyBankStatusTypes.Full)
                            {
                                <div class="breakPB">


                                <button type="button" data-toggle="modal" data-target=".breakPiggyBank"
                                        class="btn btn-primary editButton"
                                            onclick="getPiggyBankToBreak(@item.Id)">
                                        <i class="bi bi-hammer"></i>
                                </button>

                            </div>
                            }

                    </div>
                </div>

                </div>
            }
            </div>
        </div>




        <div>
            <div id="collabPB">Collaborative Piggy Banks</div>
            <div id="collabPBGrid">
            @foreach (var item in Model.CollaborativePiggyBanks)
            {
                <div class="col-md-3">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h4 class="card-title card-header headerPB">@item.PiggyBankDescription</h4>
                            <h6 class="card-subtitle mb-2 text-muted piggyBankStatus">Status : @item.PiggyBankStatusName</h6>
                            <p class="card-text">
                                <span style="font-size: 1.4em;">@item.CurrentBalance $ </span>
                                /@item.TargetSum $
                            </p>




                            <div class="editButtonDiv">


                                <button type="button" data-toggle="modal" data-target=".editCollaborativePiggyBank"
                                        class="btn btn-primary editButton"
                                        onclick="editCollaborativePiggyBank(@item.Id, getIncomes())">
                                    <i class="bi bi-pencil-fill"></i>
                                </button>

                            </div>



                            <div class="deleteButtonDiv">
                                <button type="button" data-toggle="modal" data-target=".deletePiggyBankCollab"
                                        class="btn btn-primary deleteButton" onclick="deletePiggyBankCollaboration(@item.Id)">
                                    <i class="bi bi-trash"></i>
                                </button>

                            </div>



                        </div>
                    </div>

                </div>
            }
            </div>
        </div>
    </div>







    <!--Delete PiggyBank button -->
    <div class="modal fade deletePiggyBank" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm delete</h5>
                </div>

                <div id="deletePersonalPb" class="modal-body">
                    <h5>Are you sure you want to delete this PiggyBank?</h5>
                </div>


            </div>
        </div>
    </div>




    <!--Delete PiggyBank Collaboration button -->
    <div class="modal fade deletePiggyBankCollab" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm delete</h5>
                </div>

                <div id="deleteCollab" class="modal-body">
                    <h5>Are you sure you want to delete this PiggyBank Collaboration?</h5>
                </div>

            </div>
        </div>
    </div>





    <!--Break PiggyBank button -->
    <div class="modal fade breakPiggyBank" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="breakPB">Confirm breaking this Piggy Bank</h5>
                </div>

                <div class="modal-body">
                    <h5>Are you sure you want to break this PiggyBank?</h5>
                </div>

                <form asp-action="Break" asp-controller="PiggyBank" id="breakPiggyBankForm">
                </form>


            </div>
        </div>
    </div>




</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/createOrEditPersonalPiggyBank.js" defer asp-append-version="true"></script>
    <script src="~/js/deletePiggyBank.js" defer asp-append-version="true"></script>
    <script src="~/js/breakPiggyBank.js" defer asp-append-version="true"></script>
    <script src="~/js/editPiggyBankCollaborators.js" defer asp-append-version="true"></script>
    <script src="~/js/deletePiggyBankCollaboration.js" defer asp-append-version="true"></script>
    <script src="~/js/editCollaborativePiggyBank.js" defer asp-append-version="true"></script>




    <script>
        function getIncomes() {
            return @Html.Raw(JsonConvert.SerializeObject(Model.Incomes));
        }
    </script>

}

