EWallet/Controllers/IncomeController.cs
using EWallet.BusinessLogic.Implementation.Incomes.ViewModel;
using EWallet.DataAccess;
using EWallet.WebApp.Code.Base;
using Microsoft.AspNetCore.Mvc;
using EWallet.BusinessLogic.Implementation.Incomes;
using AutoMapper;
using EWallet.Entities.Entities;
using EWallet.BusinessLogic.Implementation.Incomes.Validations;
using EWallet.Code.ExtensionMethods;
using FluentValidation;
using EWallet.BusinessLogic.Implementation.Spendings;
using EWallet.DataAccess.Enums;
using Microsoft.AspNetCore.Authorization;

namespace EWallet.Controllers
{
    [Authorize(Roles = "User")]
    public class IncomeController : BaseController
    {
        private readonly IncomeService _incomeService;
        private readonly CreateIncomeValidator _createIncomeValidator;
        private readonly EditIncomeValidator _editIncomeValidator;

        public IncomeController(ControllerDependencies dependencies, IncomeService incomesService, CreateIncomeValidator createIncomeValidator,
            EditIncomeValidator editIncomeValidator)
           : base(dependencies)
        {
            _incomeService = incomesService;
            _createIncomeValidator = createIncomeValidator;
            _editIncomeValidator = editIncomeValidator;

        }


        public async Task<IActionResult> Index()
        {
            var allIncomes = await _incomeService.GetIncomes();
            var recurrenceTypes = await _incomeService.GetRecurrenceTypesAsSelectListItems();
            
            return View(new DisplayIncomesViewModel
            {
                IncomeViewModels = allIncomes,
                RecurrenceTypes=recurrenceTypes,
            });
        }



        [HttpPost]
        public async Task<IActionResult> Create([FromBody]CreateIncomeViewModel model)
        {
            if (model == null)
            {
                return View("Error_NotFound");
            }


            var validateResult = _createIncomeValidator.Validate(model);
            if (!validateResult.IsValid)
            {
                return Ok(validateResult.GetErrorsResult());
            }
            else
            {
                await _incomeService.CreateIncome(model);
                return Ok(new { });
            };
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var income = await _incomeService.GetIncomeToEdit(id);
            return Ok(income);
        }


        [HttpPost("Income/Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _incomeService.DeleteIncome(id);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var income = await _incomeService.GetIncomeToEdit(id);
            return Ok(income);
        }

        [HttpGet]
        public async Task<IActionResult> GetLatestIncomes()
        {
            var incomes = await _incomeService.GetLatestIncomes();
            return Ok(incomes);
        }

        [HttpGet]
        public async Task<IActionResult> GetUpcomingIncomes()
        {
            var incomes = await _incomeService.GetUpcomingIncomes();
            return Ok(incomes);
        }



        [HttpPost]
        public async Task<IActionResult> Edit([FromBody] EditIncomeViewModel model)
        {
            var validateResult = _editIncomeValidator.Validate(model);
            if (!validateResult.IsValid)
            {
                return Ok(validateResult.GetErrorsResult());
            }
            else
            {
                await _incomeService.EditIncome(model);

                return Ok(new { });
            };
            
        }




    }
}

EWallet/Controllers/SpendingController.cs

using EWallet.BusinessLogic.Implementation.Spendings;
using EWallet.BusinessLogic.Implementation.Spendings.Validations;
using EWallet.BusinessLogic.Implementation.Spendings.ViewModel;
using EWallet.Common.Exceptions;
using EWallet.Common.Extensions;
using EWallet.WebApp.Code.Base;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using EWallet.Code.ExtensionMethods;
using EWallet.DataAccess.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Data.SqlClient;

namespace EWallet.Controllers
{
    [Authorize(Roles = "User")]
    public class SpendingController : BaseController
    {

        private readonly SpendingService _spendingService;
        private readonly CreateSpendingValidator _createSpendingValidator;
        private readonly EditSpendingValidator _editSpendingValidator;

        public SpendingController(ControllerDependencies dependencies, SpendingService spendingService, CreateSpendingValidator createSpendingValidator,
            EditSpendingValidator editSpendingValidator) :
            base(dependencies)
        {
            _spendingService = spendingService;
            _createSpendingValidator=createSpendingValidator;
            _editSpendingValidator = editSpendingValidator;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var allSpendings = await _spendingService.GetSpendings(pageNumber ?? 1, 5);
            var spendingCategories = await _spendingService.InitializeSpendingCategories();
            var recurrenceTypes= await _spendingService.GetRecurrenceTypesAsSelectListItems();
            var model = new DisplaySpendingViewModel
            {
                SpendingViewModels = allSpendings,
                SpendingCategories = spendingCategories,
                RecurrenceTypes = recurrenceTypes,
                PageIndex = pageNumber.GetValueOrDefault(1),
            };


            if (model.PageIndex == 1)
            {
                return View(model);
            }
            else
            {
                return Ok(model);
            }
            
        }






        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CreateSpendingViewModel model)
        {
            if (model == null)
            {
                return View("Error_NotFound");
            }

            var validateResult = _createSpendingValidator.Validate(model);
            if (!validateResult.IsValid)
            {
                return Ok(validateResult.GetErrorsResult());
            }
            else
            {
                await _spendingService.CreateSpending(model);

                return Ok(new { });
            };

           
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var spending = await _spendingService.GetCurrentSpendingToEdit(id);
            return Ok(spending);
        }


        [HttpPost("Spending/Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _spendingService.DeleteSpending(id);
            return RedirectToAction("Index");
        }


     

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            

            var spending = await _spendingService.GetCurrentSpendingToEdit(id);
            return Ok(spending);
        }


        [HttpPost]
        public async Task<IActionResult> Edit([FromBody] EditSpendingViewModel model)
        {
            var validateResult = _editSpendingValidator.Validate(model);
            if (!validateResult.IsValid)
            {
                return Ok(validateResult.GetErrorsResult());
            }
            else
            {
                await _spendingService.EditSpending(model);
                return Ok(new { });
            };
        }



        [HttpPost]
        public async Task<IActionResult> CreateSpendingCategory([FromBody] CreateSpendingCategoryViewModel model)
        {
            if (model == null)
            {
                return View("Error_NotFound");
            }

            await _spendingService.CreateSpendingCategory(model);

            return Ok(new {});
        }


        [HttpGet]
        public async Task<IActionResult> GetUpcomingSpendings()
        {
            var spendings = await _spendingService.GetUpcomingSpendings();
            return Ok(spendings);
        }




    }
}

EWallet/Controllers/TransactionController.cs
using EWallet.BusinessLogic.Implementation.Spendings;
using EWallet.BusinessLogic.Implementation.Transactions;
using EWallet.BusinessLogic.Implementation.Transactions.ViewModel;
using EWallet.DataAccess.Enums;
using EWallet.WebApp.Code.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Drawing.Printing;

namespace EWallet.Controllers
{
    [Authorize(Roles = "User")]

    public class TransactionController : BaseController
    {

        private readonly TransactionService _transactionService;


        public TransactionController(ControllerDependencies dependencies, TransactionService transactionService) :
            base(dependencies)
         { 
            _transactionService= transactionService;
        }

        public async Task<IActionResult> Index(int? pageNumber
            ,int? sortOrder, int? sortFilter, int? categoryFilter
            )
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = sortFilter;
            ViewData["CurrentCategory"] = categoryFilter;
            
            var transactionCount = await _transactionService.GetFilteredTransactionsCount(categoryFilter);
            var totalPages = (int)Math.Ceiling(transactionCount / (double)10);

            if (pageNumber > totalPages)
            {
                pageNumber = totalPages;
            }
            var transactionCategories = _transactionService.InitializeTransactionCategories();
            var allTransactions = await _transactionService.GetTransactions(pageNumber ?? 1, 10, sortOrder, sortFilter, categoryFilter);            

            DisplayTransactionViewModel displayTransactionVM = new DisplayTransactionViewModel()
            {
                TansactionCategories = transactionCategories,
                TransactionViewModels=allTransactions,
                PageIndex =pageNumber.GetValueOrDefault(1),
                TotalPages = totalPages

        };

            return View(displayTransactionVM);
          
        }

    }
}

EWallet/Views/Shared/Index.cshtml
@using EWallet.BusinessLogic;
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

@*@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}*@

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

EWallet/Views/Shared/InternalServerError.cshtml
@using EWallet.BusinessLogic;
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 500</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

EWallet/Views/Shared/NotFound.cshtml
@using EWallet.BusinessLogic;
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 404</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

EWallet/Views/Shared/Unauthorized.cshtml
@using EWallet.BusinessLogic;
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 301</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

EWallet/Views/Shared/_Layout.cshtml

@inject EWallet.BusinessLogic.Implementation.Users.ViewModel.CurrentUserViewModel CurrentUser;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EWallet</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" defer asp-append-version="true"></script>
    <script src="~/js/utils.js" defer asp-append-version="true"></script>
    <script src="~/js/getCurrentBalance.js" defer asp-append-version="true"></script>
   



</head>
<body>
    <div class="wrapper">
        <div class="container-layout">
            <div id="sidebar">


                <div class="menu">
                    <div id="appName"> <a id="appNameLink" asp-controller="Home" asp-action="Index"><img id="logo" src="~/img/71592.png"/>Wallet</a></div>
                    <div id="menuLinks">
                    <a asp-controller="Home" asp-action="Index">Home</a>
                    <a asp-controller="Spending" asp-action="Index">Spendings</a>
                    <a asp-controller="Income" asp-action="Index">Incomes</a>
                    <a asp-controller="PiggyBank" asp-action="Index">PiggyBank</a>              
                    <a asp-controller="Transaction" asp-action="Index">Transaction</a>
                    </div>

                </div>

            </div>

            <div class="main @ViewData["Class"]">
                
                <header>
                    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                        <div class="container">
                           
                                @if (CurrentUser.IsAuthenticated)
                                {

                                <div>
                                    <span id="helloUser">Hello, @CurrentUser.Username!</span>
                                    
                                </div>

                                        <div id="currentBalanceDiv">

                                            <div id="currentBalance">
                                                <div>
                                                    <span id="moneyIcon">
                                                        <i class="bi bi-cash-coin"></i>
                                                    </span>
                                                </div>
                                                <div id="currentBalanceData">
                                                   
                                                </div>
                                            </div>


                                            <div id="currentSavings">
                                                <div>
                                                    <span id="piggyBankIcon">
                                                        <i class="bi bi-piggy-bank-fill"></i>
                                                    </span>
                                                </div>
                                                <div id="savingsContent">
                                                   
                                                </div>
                                            </div>

                                        </div>
                                   
                                       
                                <div id="logOut">
                                    <a asp-controller="User" asp-action="Logout" class="btn logout">Log out</a>
                                </div>

                                }
                                else
                                {
                                    <div>
                                    <a asp-controller="User" asp-action="Register" class="btn btn-primary registerButtons">Register As User</a>
                                    <a asp-controller="User" asp-action="RegisterAdvisor" class="btn btn-primary registerButtons">Register As Advisor</a>
                                    </div>
                                }
                        </div>
                    </nav>
                </header>
                

                <main role="main" class="pb-3">



                    <div id="content">
                        
                        @RenderBody()
                
                    </div>

                </main>
            </div>

        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - EWallet.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        @RenderSection("Scripts", required: false)

    </div>
</body>
</html>